<a href="https://colab.research.google.com/github/RayalaNK/Airbnb-Seattle-DataAnalysis/blob/master/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [6]:
torch.*Tensor?

In [9]:
torch.nn.Module??

In [13]:
!ls -lh

total 4.0K
drwxr-xr-x 1 root root 4.0K Apr 21 13:39 sample_data


In [15]:
%%bash
# List all the files but with cleaner outputs for readability
for f in $(ls *); do
    echo $(wc -l $f)
done

wc: anscombe.json: No such file or directory
wc: california_housing_test.csv: No such file or directory
wc: california_housing_train.csv: No such file or directory
wc: mnist_test.csv: No such file or directory
wc: mnist_train_small.csv: No such file or directory
wc: README.md: No such file or directory


In [16]:
%magic

In [18]:
t = torch.Tensor(2,3,4)
type(t)

torch.Tensor

In [19]:
t.size()

torch.Size([2, 3, 4])

In [20]:
print("t size:", '\u00D7 '.join(map(str, t.size())))

t size: 2× 3× 4


In [21]:

# prints dimensional space and sub-dimensions
print(f'point in a {t.numel()} dimensional space')
print(f'organised in {t.dim()} sub-dimensions')

point in a 24 dimensional space
organised in 3 sub-dimensions


In [22]:
# Mind the underscore!
# Any operation that mutates a tensor in-place is post-fixed with an _.
# For example: x.copy_(y), x.t_(), x.random_(n) will change x.
t.random_(10)

tensor([[[8., 7., 4., 7.],
         [5., 0., 8., 7.],
         [2., 5., 4., 3.]],

        [[4., 7., 3., 7.],
         [3., 2., 6., 4.],
         [4., 2., 1., 7.]]])

In [27]:
# This resizes the tensor permanently 
r = torch.Tensor(t)
r.resize_(3, 2, 2)
r

tensor([[[8., 7.],
         [4., 7.]],

        [[5., 0.],
         [8., 7.]],

        [[2., 5.],
         [4., 3.]]])

In [29]:
s = r.clone()
s

tensor([[[8., 7.],
         [4., 7.]],

        [[5., 0.],
         [8., 7.]],

        [[2., 5.],
         [4., 3.]]])

In [30]:
s.fill_(1)
s

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [31]:
r

tensor([[[8., 7.],
         [4., 7.]],

        [[5., 0.],
         [8., 7.]],

        [[2., 5.],
         [4., 3.]]])

In [32]:
# Creates a 1D tensor of integers 1 to 4
v = torch.Tensor([1, 2, 3, 4])
v

tensor([1., 2., 3., 4.])

In [34]:
# Print number of dimensions (1D) and size of tensor
v.size()
print(f'dim: {v.dim()}, size: {v.size()[0]}')

dim: 1, size: 4


In [37]:
w = torch.Tensor([1, 0, 2, 0])
w

tensor([1., 0., 2., 0.])

In [39]:
# Element-wise multiplication
v * w

tensor([1., 0., 6., 0.])

In [40]:
# Scalar product: 1*1 + 2*0 + 3*2 + 4*0
v @ w

tensor(7.)

In [43]:
# In-place replacement of random number from 0 to 10
x = torch.Tensor(5).random_(100)
x

tensor([82., 35., 47., 63., 76.])

In [44]:
print(f'first: {x[0]}, last: {x[-1]}')

first: 82.0, last: 76.0


In [45]:
# Extract sub-Tensor [from:to)
x[1:2 + 1]

tensor([35., 47.])

In [46]:
v

tensor([1., 2., 3., 4.])

In [47]:
v = torch.arange(1, 4+1)
v

tensor([1, 2, 3, 4])

In [48]:
# Square all elements in the tensor
print(v.pow(2), v)

tensor([ 1,  4,  9, 16]) tensor([1, 2, 3, 4])


**Matrices (2D Tensors)**